[package]
name = "usor-solana"
version = "0.1.0"
description = "USOR Tech - Strategic Digital Oil Reserve Program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "usor_solana"

[dependencies]
anchor-lang = "0.29.0"
